default:
  image: ubuntu:20.04-docs

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - yarn install
  - yarn build
  - ssh docs@192.168.2.14 rm -rf /tank/docs/build
  - scp -r build docs@192.168.2.14:/tank/docs/
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - yarn install
  - yarn build
  - mv ./build ../public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
