default:
  image: ubuntu:20.04-docs

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - yarn install
  - yarn build
  - mv ./build ../public
  - scp -r ../public docs@192.168.2.14:/tank/docs
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - yarn install
  - yarn build
  - mv ./build ../public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
