repos:
  - repo: https://github.com/radxa-docs/pre-commit-hooks
    rev: 25990488674e481745f6e6c08ed5acbfd1cf2ebc
    hooks:
      - id: remove-unreferenced-image
      - id: use-webp-image
      - id: fix-en-dash-list
      - id: tab-with-querystring-undefined
      - id: tab-without-querystring
      - id: no-full-uri-for-internal-pages
      - id: check-external-links
      - id: disable-sidebar_label
      - id: index-to-README
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
        args: [-x]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.23
    hooks:
      - id: typos
