name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  id-token: write
  pages: write

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: pre-commit check
        if: github.event_name != 'merge_group'
        run: |
          pip install pre-commit
          if [ "${{ github.event_name }}" == "pull_request" ] || \
             [ "${{ github.event.forced }}" == "true" ]
          then
            git fetch origin ${{ github.event.before }}:old_head
          fi
          if ! pre-commit run --from-ref ${{ github.event.before }} --to-ref ${{ github.event.after }} --show-diff-on-failure
          then
            echo '=== Detected code style issue! ==='
            echo 'Suggest changes are listed above.'
            echo 'Please install pre-commit and run `pre-commit run --all-files` to fix it.'
            echo 'Strongly recommended to run `pre-commit install` in your local project!'
            echo 'You can learn more abour pre-commit from https://pre-commit.com/'
            exit 1
          fi
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: "./build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        if: github.event_name != 'pull_request' && github.event_name != 'merge_group'
