name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  id-token: write
  pages: write

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: pre-commit check
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends webp
          pip install pre-commit
          if ! pre-commit run --all-files --show-diff-on-failure
          then
            echo ''
            echo '=== Code style issue detected! ==='
            echo 'Suggest changes are listed above.'
            echo 'Please install pre-commit and run `pre-commit run --all-files` to fix it.'
            echo 'Strongly recommended to run `pre-commit install` to catch issues before pushing.'
            echo 'You can learn more abour pre-commit from https://pre-commit.com/'
            exit 1
          fi
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: "./build"
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v3
        continue-on-error: true
        if: github.event_name != 'pull_request' && github.event_name != 'merge_group'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        if: steps.setup-pages.outcome == 'success'
